In [36]:
import cv2
img = cv2.imread('img.png')
print(img.shape)

(172, 180, 3)


In [37]:
print(img)

[[[ 58  35  33]
  [ 57  33  30]
  [ 54  29  25]
  ...
  [  7   6   8]
  [  8   8   9]
  [ 10  10  11]]

 [[ 60  36  34]
  [ 60  34  31]
  [ 56  30  26]
  ...
  [  6   6   8]
  [  8   7   9]
  [ 10   9  10]]

 [[ 61  37  34]
  [ 62  36  32]
  [ 60  33  29]
  ...
  [  6   5   7]
  [  7   7   8]
  [  9   9  10]]

 ...

 [[157 108  88]
  [154 106  88]
  [144  96  80]
  ...
  [ 20  12  14]
  [ 23  13  15]
  [ 24  14  17]]

 [[139  89  69]
  [134  86  68]
  [124  77  61]
  ...
  [ 22  13  15]
  [ 24  14  17]
  [ 25  15  18]]

 [[121  72  53]
  [116  69  52]
  [107  61  46]
  ...
  [ 22  14  17]
  [ 23  15  18]
  [ 25  16  19]]]


In [23]:
print(img[0,2,:])

[54 29 25]


In [40]:
# 行（高さ）を取得
print(img[0, :, :].shape)
print(img[0, :, :])

(180, 3)
[[58 35 33]
 [57 33 30]
 [54 29 25]
 [52 27 23]
 [52 27 23]
 [56 31 26]
 [62 38 34]
 [59 38 34]
 [48 29 26]
 [42 25 22]
 [40 24 23]
 [39 25 24]
 [38 26 26]
 [38 27 28]
 [38 29 29]
 [38 30 30]
 [37 30 29]
 [36 30 28]
 [35 29 27]
 [34 28 26]
 [35 28 25]
 [35 29 25]
 [38 30 27]
 [42 31 28]
 [46 32 30]
 [49 32 32]
 [50 32 33]
 [48 31 33]
 [44 29 31]
 [43 29 32]
 [44 32 35]
 [40 29 33]
 [30 20 25]
 [29 20 26]
 [38 29 35]
 [44 35 40]
 [46 37 41]
 [47 37 41]
 [47 37 39]
 [49 39 39]
 [54 42 41]
 [56 43 40]
 [56 43 38]
 [57 42 37]
 [58 42 37]
 [57 41 35]
 [55 38 32]
 [50 34 28]
 [45 30 24]
 [44 29 24]
 [46 32 27]
 [48 35 32]
 [52 40 38]
 [54 43 42]
 [54 43 43]
 [55 43 43]
 [56 42 43]
 [57 42 43]
 [58 43 44]
 [58 43 44]
 [57 43 43]
 [56 43 43]
 [57 45 44]
 [56 44 43]
 [51 41 40]
 [48 38 37]
 [45 36 34]
 [45 37 34]
 [47 40 37]
 [46 40 36]
 [40 35 30]
 [42 37 32]
 [51 46 41]
 [54 49 44]
 [52 47 42]
 [51 45 40]
 [51 44 38]
 [51 43 38]
 [52 44 38]
 [54 45 40]
 [56 47 42]
 [58 48 44]
 [60 49

In [42]:
# 列（幅）を取得
print(img[:, 0, :].shape)
print(img[:, 0, :])

(172, 3)
[[ 58  35  33]
 [ 60  36  34]
 [ 61  37  34]
 [ 62  36  34]
 [ 61  35  33]
 [ 62  35  33]
 [ 64  37  34]
 [ 65  37  34]
 [ 65  38  35]
 [ 65  37  34]
 [ 63  35  32]
 [ 62  34  31]
 [ 61  34  31]
 [ 62  35  31]
 [ 63  37  33]
 [ 63  37  34]
 [ 64  38  35]
 [ 64  38  35]
 [ 64  38  35]
 [ 64  37  34]
 [ 65  36  32]
 [ 66  36  31]
 [ 66  36  31]
 [ 66  36  31]
 [ 66  36  32]
 [ 67  36  32]
 [ 67  36  32]
 [ 67  36  32]
 [ 67  36  33]
 [ 68  36  33]
 [ 68  36  33]
 [ 69  36  33]
 [ 69  36  33]
 [ 70  36  33]
 [ 70  36  33]
 [ 71  37  34]
 [ 73  39  36]
 [ 74  40  37]
 [ 75  40  37]
 [ 76  40  37]
 [ 76  40  37]
 [ 77  41  37]
 [ 78  42  37]
 [ 78  42  37]
 [ 79  43  38]
 [ 80  44  38]
 [ 80  44  38]
 [ 81  45  38]
 [ 81  45  38]
 [ 81  46  38]
 [ 82  46  38]
 [ 83  45  39]
 [ 84  45  40]
 [ 85  45  41]
 [ 86  44  41]
 [ 86  44  41]
 [ 87  45  42]
 [ 87  45  42]
 [ 87  45  42]
 [ 87  45  42]
 [ 87  45  42]
 [ 87  46  42]
 [ 87  46  42]
 [ 87  46  42]
 [ 88  46  43]
 [ 88  46  43]
 

In [43]:
# 奥行き（チャネル）を取得
print(img[:, :, 0].shape)
print(img[:, :, 0])

(172, 180)
[[ 58  57  54 ...   7   8  10]
 [ 60  60  56 ...   6   8  10]
 [ 61  62  60 ...   6   7   9]
 ...
 [157 154 144 ...  20  23  24]
 [139 134 124 ...  22  24  25]
 [121 116 107 ...  22  23  25]]


In [7]:
import numpy as np
array = np.zeros((100, 100, 3))
print(array.shape)

(100, 100, 3)


In [8]:
print(array)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


# 最初の数字が三次元目の軸（奥行き方向）、2番目が二次元目の軸（縦）、3番目が一次元目（横）

In [12]:
X = np.array(
    [[[1,  2,  3],
    [4,  5,  6]],

    [[7,  8,  9],
    [10, 11, 12]]])
X

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
X.shape

(2, 2, 3)

In [13]:
Y = np.array([[[1]]])
Y

array([[[1]]])

In [33]:
Y.shape

(1, 1, 1)

In [34]:
X[0, 1, 2] # 奥行き0, 高さ1, 幅2のところの値をとってくる

6

In [35]:
X[0, :, :] # 奥行き軸(axis=0)の0番目を取り出す

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
X[:, 1, :] # 縦軸(axis=1)の1番目を取り出す

array([[ 4,  5,  6],
       [10, 11, 12]])

In [20]:
X[:, :, 2] # 横軸(axis=2)の２番目を取り出す

array([[ 3,  6],
       [ 9, 12]])